# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class G4starter < Formula
  desc "Interactive cli tool for generating geant4 simulation projects"
  homepage "https://github.com/evandde/G4Starter"
  url "https://github.com/evandde/G4Starter/archive/refs/tags/v0.1.3.tar.gz"
  sha256 "0bc52a8b18839e164e7fcecdcfa81543911308ad4d615140beecc28544567346"
  license "MIT"

  on_macos do
  end

  def install
    bin.install "G4Starter_mac" => "g4starter"
  end
end
