# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class G4starter < Formula
  desc "Interactive cli tool for generating geant4 simulation projects"
  homepage "https://github.com/evandde/G4Starter"
  url "https://github.com/evandde/G4Starter/archive/refs/tags/v0.2.0.tar.gz"
  sha256 "dfe2940eb77ff1f0b4e7e2efb39b8ea8c9bf1730caf9f61bd421299c6d60cc34"
  license "MIT"

  on_macos do
  end

  def install
    bin.install "G4Starter_mac" => "g4starter"
  end
end
